// Original starter content for CPST Chaos, seeded into the "Standard Issue" pack on first start.
// Keys are stable so re-seeding never duplicates prompts and moderator edits are kept.

export const SEED_CATEGORIES = ["general", "corn", "science", "containment", "bureaucracy", "cosmic"];

export const STANDARD_PACK = {
  name: "Standard Issue",
  description: "The official CPST incident library. Approved by nobody in particular.",
};

type Seed = [key: string, category: string, text: string];

const SAFE: Seed[] = [
  ["s01", "science", "The CPST research team accidentally invented ____."],
  ["s02", "corn", "The worst thing to find inside a classified corn silo."],
  ["s03", "containment", "The new containment procedure is just ____."],
  ["s04", "science", "Scientists have discovered that corn can ____."],
  ["s05", "containment", "The entity's greatest weakness is embarrassingly ____."],
  ["s06", "general", "What the Strike Team's secret handshake actually looks like."],
  ["s07", "cosmic", "The real reason the Corn Sun flickers every Tuesday."],
  ["s08", "general", "A rejected name for a Strike Team tactical vehicle."],
  ["s09", "containment", "The most useless item in a standard-issue containment kit."],
  ["s10", "bureaucracy", "What the CPI Exec keeps in the locked drawer."],
  ["s11", "bureaucracy", "The inspirational poster in the Records Division breakroom says: \"____\""],
  ["s12", "corn", "The first words ever spoken by a sentient ear of corn."],
  ["s13", "corn", "A warning label that should be printed on every cob."],
  ["s14", "cosmic", "The worst possible code name for a Cosmic-class entity."],
  ["s15", "cosmic", "What the orbiting planets are secretly arguing about."],
  ["s16", "general", "The strangest item on the Strike Team cafeteria menu."],
  ["s17", "corn", "A terrible slogan for Corn Planet tourism."],
  ["s18", "containment", "What actually happens during a \"Level 4 Kernel Event.\""],
  ["s19", "containment", "The one question you should never ask a Neutralized entity."],
  ["s20", "bureaucracy", "The Strike Team's official policy on popcorn."],
  ["s21", "general", "The most suspicious thing a new recruit could say during orientation."],
  ["s22", "containment", "The containment cell is fine, except it smells like ____."],
  ["s23", "bureaucracy", "A brand-new classification level, somehow less dangerous than LOCAL."],
  ["s24", "bureaucracy", "What the Records Division redacted from the last incident report."],
  ["s25", "containment", "The entity escaped because someone left out ____."],
  ["s26", "science", "An unexpected side effect of eating corn grown in zero gravity."],
  ["s27", "general", "The worst thing to hear over the facility intercom at 3 AM."],
  ["s28", "corn", "A motivational speech from a corn cob, in five words or fewer."],
  ["s29", "bureaucracy", "What the Strike Team Overseer does on their day off."],
  ["s30", "bureaucracy", "A totally normal thing that is now, somehow, classified."],
  ["s31", "containment", "The password to the main containment vault is probably ____."],
  ["s32", "general", "The least intimidating battle cry for the Strike Team."],
  ["s33", "cosmic", "What the Corn Sun would post on social media."],
  ["s34", "bureaucracy", "A rejected title for the Strike Team training manual."],
  ["s35", "bureaucracy", "A new facility rule added after \"the incident.\""],
  ["s36", "general", "The name of the Strike Team's emotional support animal."],
  ["s37", "cosmic", "What the planets were doing before they started orbiting corn."],
  ["s38", "containment", "A reason to evacuate Sector 7 that isn't a containment breach."],
  ["s39", "cosmic", "The worst gift to give a Cosmic-class entity."],
  ["s40", "general", "The Strike Team's most embarrassing mission patch."],
  ["s41", "science", "What the scanner means when it beeps \"ANOMALOUS BUTTER DETECTED.\""],
  ["s42", "bureaucracy", "A job listing for the least desirable position on Corn Planet."],
  ["s43", "general", "The final line of every CPST recruitment video."],
  ["s44", "science", "What's actually inside a standard-issue Kernel Grenade."],
  ["s45", "containment", "The entity refuses to be contained until it gets ____."],
  ["s46", "general", "The secret ingredient in the facility's mystery casserole."],
  ["s47", "bureaucracy", "A lie detector question that nobody on the Strike Team passes."],
  ["s48", "science", "The weirdest thing written on the research lab whiteboard."],
  ["s49", "containment", "A much worse name for \"containment breach.\""],
  ["s50", "corn", "The one thing you should never microwave on Corn Planet."],
  ["s51", "bureaucracy", "What the security cameras caught the Records Division doing."],
  ["s52", "bureaucracy", "An unhelpful tip from the CPST safety handbook."],
  ["s53", "general", "The Strike Team theme song is mostly just ____."],
  ["s54", "general", "What your clearance badge photo secretly reveals about you."],
  ["s55", "corn", "A new holiday celebrated only on Corn Planet."],
  ["s56", "corn", "The villain origin story of a very angry corn husk."],
  ["s57", "general", "How the Strike Team settles arguments."],
  ["s58", "containment", "Something you should not bring to a containment hearing."],
  ["s59", "bureaucracy", "The rarest classification ever assigned: ____."],
  ["s60", "cosmic", "What the Corn Sun whispers when nobody is listening."],
];

const CHAOS: Seed[] = [
  ["c01", "bureaucracy", "The most unhinged thing to write in a resignation letter to the CPI Exec."],
  ["c02", "containment", "The real reason the last intern was reclassified as an entity."],
  ["c03", "containment", "The most chaotic way to fail a containment drill."],
  ["c04", "bureaucracy", "A deeply unsettling thing to find in your own personnel file."],
  ["c05", "science", "The worst thing to say out loud while being scanned for anomalies."],
  ["c06", "general", "What the Strike Team would do with unlimited budget and zero oversight."],
  ["c07", "bureaucracy", "The group chat name the Overseers don't want you to see."],
  ["c08", "corn", "The most cursed crossover between corn and a household appliance."],
  ["c09", "containment", "A breach report that would get its author fired immediately."],
  ["c10", "general", "The real ingredients of the bunker's \"nutritional paste.\""],
  ["c11", "bureaucracy", "A conspiracy theory that Records Division has, unfortunately, confirmed."],
  ["c12", "containment", "The most passive-aggressive note ever taped to a containment cell door."],
  ["c13", "containment", "What the entity in Cell 9 has been writing on the walls."],
  ["c14", "science", "The worst possible moment to start the self-destruct sequence."],
  ["c15", "cosmic", "The dumbest reason a planet has ever been knocked out of orbit."],
  ["c16", "bureaucracy", "The new punishment for agents who microwave fish in the breakroom."],
  ["c17", "corn", "The most chaotic thing to shout during a moment of silence for fallen corn."],
  ["c18", "science", "An experiment that was definitely not approved by the ethics board."],
  ["c19", "general", "The thing everyone on the Strike Team pretends not to know about."],
  ["c20", "cosmic", "What the Corn Sun's search history looks like."],
  ["c21", "containment", "The most humiliating way to be neutralized."],
  ["c22", "science", "A terrible plan for weaponizing popcorn."],
  ["c23", "science", "The real reason COB-AI, the facility computer, keeps asking for a lawyer."],
  ["c24", "bureaucracy", "The CPI Exec's most unhinged 3 AM memo."],
  ["c25", "bureaucracy", "The worst thing to accidentally reply-all to the entire facility."],
  ["c26", "general", "A cursed item confiscated from a new recruit's locker."],
  ["c27", "science", "The side effect listed at the very bottom of the anti-anomaly pills."],
  ["c28", "cosmic", "What gets you permanently banned from the Corn Planet space station."],
  ["c29", "containment", "Item number one on the escaped entity's list of demands."],
  ["c30", "containment", "A containment breach that is somehow entirely your fault. Explain."],
];

export const SEED_PROMPTS = [
  ...SAFE.map(([key, category, text]) => ({ key: `std-${key}`, category, text, rating: "safe" as const })),
  ...CHAOS.map(([key, category, text]) => ({ key: `std-${key}`, category, text, rating: "chaos" as const })),
];

/** Used only if the database somehow has no usable prompts at all. */
export const EMERGENCY_PROMPTS = [
  "Explain the containment breach. Be specific.",
  "The incident report just says ____.",
  "What went wrong in Sector 7 today?",
  "The Strike Team's excuse for being late.",
];
